In [13]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [19]:

import pandas as pd

from utils import feature_engineering

In [9]:
df = pd.read_csv("../data/processed/karachi_training_data.csv")

In [10]:
df.head()

,timestamp,pm2_5,pm10,no2,o3,so2,co,us_aqi,temperature_2m,relative_humidity_2m,wind_speed_10m,pressure_msl,precipitation,cloud_cover
0,2024-01-01 00:00:00+00:00,46.2,68.9,6.7,97.0,19.9,598.0,113.552080,15.30,64.526280,11.923557,1017.5,0.0,0.0
1,2024-01-01 01:00:00+00:00,47.1,70.1,14.8,89.0,20.4,689.0,113.708330,14.95,66.666610,12.413477,1018.0,0.0,0.0
2,2024-01-01 02:00:00+00:00,49.1,72.6,25.8,78.0,21.2,812.0,113.885414,14.65,68.428215,12.594856,1018.9,0.0,0.0
3,2024-01-01 03:00:00+00:00,51.8,76.1,31.8,77.0,22.2,887.0,114.104164,15.20,66.271194,13.044722,1019.2,0.0,0.0
4,2024-01-01 04:00:00+00:00,53.0,77.5,28.3,95.0,23.6,872.0,114.343750,17.60,57.268930,11.966954,1019.8,0.0,1.0

In [16]:
engineered_df = feature_engineering.engineer_features(feature_engineering.clean_raw_data(df))

In [17]:
engineered_df.head()

,timestamp,pm2_5,pm10,no2,o3,so2,co,us_aqi,temperature_2m,relative_humidity_2m,...,aqi_lag_48h,pm2_5_lag_48h,aqi_lag_72h,pm2_5_lag_72h,aqi_change_rate_1h,aqi_change_rate_24h,target_aqi_24h,target_aqi_48h,target_aqi_72h,has_target
0,2024-01-01 00:00:00+00:00,46.2,68.9,6.7,97.0,19.9,598.0,113.552080,15.30,64.526280,...,NaN,NaN,NaN,NaN,NaN,NaN,99.606920,122.833320,104.499990,1
1,2024-01-01 01:00:00+00:00,47.1,70.1,14.8,89.0,20.4,689.0,113.708330,14.95,66.666610,...,NaN,NaN,NaN,NaN,0.156250,NaN,98.270450,123.979164,103.770840,1
2,2024-01-01 02:00:00+00:00,49.1,72.6,25.8,78.0,21.2,812.0,113.885414,14.65,68.428215,...,NaN,NaN,NaN,NaN,0.177084,NaN,96.973274,124.812490,103.302086,1
3,2024-01-01 03:00:00+00:00,51.8,76.1,31.8,77.0,22.2,887.0,114.104164,15.20,66.271194,...,NaN,NaN,NaN,NaN,0.218750,NaN,95.770440,125.437510,102.937490,1
4,2024-01-01 04:00:00+00:00,53.0,77.5,28.3,95.0,23.6,872.0,114.343750,17.60,57.268930,...,NaN,NaN,NaN,NaN,0.239586,NaN,94.756290,125.916670,102.479160,1

In [22]:
OUTPUT_FILENAME = "karachi_features_targets.csv"

project_root = Path.cwd().parent  
local_dir = project_root / "data" / "engineered"
local_dir.mkdir(parents=True, exist_ok=True)

local_path = local_dir / OUTPUT_FILENAME

engineered_df.to_csv(local_path, index=False)
print(f"Saved to: {local_path.resolve()}")

Saved to: C:\Users\rzulf\OneDrive\Documents\AQI_predictor\data\engineered\karachi_features_targets.csv